# Core Coraza Configuration
# Set the engine mode to On (or DetectionOnly)
SecRuleEngine On

# Response body limits
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml
SecResponseBodyLimit 524288
SecResponseBodyLimitAction ProcessPartial

# Audit logs
SecAuditEngine RelevantOnly
SecAuditLog /var/log/coraza/audit.log
SecAuditLogFormat JSON
SecAuditLogType Serial

# Timeouts
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
